### PR TITLE
load from File/Blob on front-end

### PR DESCRIPTION
**Pull request by jcphill**
Use geotiff package fromBlob() function to read File/Blob object
directly rather than copying data to ArrayBuffer object or using
createObjectURL() to create URL string for File/Blob object.

### CODE REVIEW

**Comment by jcphill** [comment]
Closes #55.

**Comment by DanielJDufour** [comment]
Awesome! I'll take a look.

**Comment by DanielJDufour** [comment]
Looks great.  Thanks for the contribution.

**Comment by jcphill** [comment]
Thanks!

**Pull request merged**
