### PR TITLE
patch geotiff to avoid redundant reads of pixel-interleaved files

### PR DESCRIPTION
**Pull request by jcphill**
Backport https://github.com/geotiffjs/geotiff.js/pull/380

### CODE REVIEW

**Comment by DanielJDufour** [comment]
Would this just be temporary until a new version of geotiff.js is released?

**Comment by jcphill** [comment]
Until a new geotiff version is released and georaster is updated to work with it.

**Comment by DanielJDufour** [comment]
I think I'd be comfortable merging and publishing under a `georaster@next` tag.  Would that work for you?

**Comment by jcphill** [comment]
I don't care about the tag, and assume it would be included in @latest eventually.
Hold off on publishing until today's merge regression is fixed, though.

**Review by DanielJDufour — APPROVED** [review]

**Pull request merged**
